- type: job
  id: Mercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400
    - !type:WhitelistRequirement
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconMercenary" #
  supervisors: job-supervisors-hire
  setPreference: true
  access:
  - Maintenance
  - External
  - Mercenary

- type: startingGear
  id: MercenaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    back: ClothingBackpackMercFilled 
    shoes: ClothingShoesBootsMercFilled
    # shoes: ClothingShoesBootsMagMercenaryFilled # Give this only to new spawns
    mask: ClothingMaskGasMerc
    eyes: ClothingEyesGlassesMercenary
    gloves: ClothingHandsMercGlovesCombat
#    head: ClothingHeadHatBeretMercenary
    head: ClothingHeadHelmetMerc
    outerClothing: ClothingOuterVestWebMerc
    id: MercenaryPDA
    ears: ClothingHeadsetGrey 
    belt: ClothingBeltMercWebbing
    pocket1: WeaponPistolPollock
  innerClothingSkirt: ClothingUniformJumpskirtMercenary
  satchel: ClothingBackpackSatchelMercFilled 
  duffelbag: ClothingBackpackDuffelMercFilled 